### ISSUE TITLE
Install doctrine fixtures

### ISSUE THREAD

**Issue by msvrtan** [NullTraining/project-team3#45]
Package name: doctrine/doctrine-fixtures-bundle

(it's a dev dependency)

In `config/packages/dev` and `config/packages/test` you need to add `fixtures.yaml` with:

```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #register data fixtures
    App\DataFixtures\ORM\:
        resource: '../../../src/DataFixtures/ORM'
        tags: ['doctrine.fixture.orm']

```
